deps:
  vault:
    url: https://releases.hashicorp.com/vault/1.1.3/vault_1.1.3_linux_amd64.zip
    version: 1.1.3

  safe:
    url: https://github.com/starkandwayne/safe/releases/download/v1.2.1/safe-linux-amd64
    version: 1.2.1

  spruce:
    url: https://github.com/geofffranks/spruce/releases/download/v1.20.0/spruce-linux-amd64
    version: 1.20.0

  jq:
    url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 \
    version: 1.6

  bosh:
    url: https://github.com/cloudfoundry/bosh-cli/releases/download/v5.5.1/bosh-cli-5.5.1-linux-amd64
    version: 5.5.1

  genesis:
    url: https://github.com/genesis-community/genesis/releases/download/v2.6.16/genesis
    version: 2.6.16
